version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.test
    depends_on:
      - mongo
    command: pnpm run test

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_test_data:/data/db

volumes:
  mongodb_test_data:
